//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIVOSHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductOrder
    {
        [DisplayName("เลขที่การขาย")]
        public int Order_Id { get; set; }
        [DisplayName("รหัสสมาชิก")]
        public int User_Id { get; set; }
        [DisplayName("วันที่การขาย")]
        public System.DateTime Order_Date { get; set; }
        [DisplayName("ยอดสุทธิ")]
        public decimal Order_Price { get; set; }
        [DisplayName("รูปภาพ")]
        public string Order_Picture { get; set; }
        [DisplayName("สถานะ")]
        public string Order_Status { get; set; }
        [DisplayName("หมายเลขพัสดุ")]
        public string Order_Parcel { get; set; }
    
        public virtual UserAccout UserAccout { get; set; }
    }
}
